- include/boost/algorithm/hex.hpp
- test/hex_test1.cpp
https://svn.boost.org/trac/boost/ticket/7064
`boost::algorithm::hex` supports binary to hex string conversion, but as upper case ABCDEF.
This adds `boost::algorithm::hex_lower` for lower-case hex string output.
> Implement algorithm::hex_lower (Trac ticket #7064)

- include/boost/algorithm/hex.hpp
- test/hex_test1.cpp
https://svn.boost.org/trac/boost/ticket/7064
boost::algorithm::hex supports binary to hex string conversion, but as upper case ABCDEF.
This adds boost::algorithm::hex_lower for lower-case hex string output.
> Implement algorithm::hex_lower #7064 (rebased on develop)

- minmax/example/minmax_ex.cpp
I got compilation error, because of using of undeclared identifier 'front_inserter'.
I checked that [std::front_inseter](http://www.cplusplus.com/reference/iterator/front_inserter) is defined at [\<iterator\>](http://www.cplusplus.com/reference/iterator) header, which probably is missed here. 
So this fix is just about adding one more include of  [\<iterator\>](http://www.cplusplus.com/reference/iterator) to the sample.
Checked with VS 2015 community.
> Fix missing include <iterator>

- doc/all_of.qbk
- doc/any_of.qbk
- doc/is_partitioned.qbk
- doc/is_permutation.qbk
- doc/none_of.qbk
- doc/partition_point.qbk
- include/boost/algorithm/cxx11/all_of.hpp
- include/boost/algorithm/cxx11/any_of.hpp
- include/boost/algorithm/cxx11/copy_if.hpp
- include/boost/algorithm/cxx11/copy_n.hpp
- include/boost/algorithm/cxx11/find_if_not.hpp
- include/boost/algorithm/cxx11/iota.hpp
- include/boost/algorithm/cxx11/is_partitioned.hpp
- include/boost/algorithm/cxx11/is_permutation.hpp
- include/boost/algorithm/cxx11/is_sorted.hpp
- include/boost/algorithm/cxx11/none_of.hpp
- include/boost/algorithm/cxx11/partition_copy.hpp
- include/boost/algorithm/cxx11/partition_point.hpp
- include/boost/algorithm/cxx14/equal.hpp
- include/boost/algorithm/cxx14/is_permutation.hpp
- include/boost/algorithm/cxx14/mismatch.hpp
As a result of commit 4dac507 (Remove code to use standard library versions of algorithms), most of the files in cxx11 were including `<algorithm>` unnecessarily.
I suggest removing those includes where they are not used, and also removing comments which misleadingly said "We will use the standard one if it is available, otherwise we have our own implementation."
Also, the file copy_if.hpp wasn't including `<utility>` where pair and make_pair can be found, and partition_point was missing an `#include <iterator>`.
A second commit removes similar unused includes in cxx14/is_permutation.hpp and cxx14/mismatch.hpp, and adds a missing `#include <iterator>` to cxx14/equal.hpp.
A third commit removes incorrect statements from the docs.
> Remove some includes, fix some comments and docs

- include/boost/algorithm/hex.hpp
boost/exception/errinfo_errno.hpp, included in boost/exception/all.hpp, pushes the warning level to 1 on MSVC, but emits a level 1 warning with /sdl. Only exception.hpp and throw_exception.hpp are necessary.
> Remove unused bad include

- doc/is_palindrome.qbk
- example/is_palindrome_example.cpp
- include/boost/algorithm/is_palindrome.hpp
- test/is_palindrome_test.cpp
I think, this is the best way to solve problem with 'is_palindrome' and 'const char*' . If user will try to use const char* with is_palindrome, user will get a compile error.
Also i updated documentation.
> Disabled 'is_palindrome' with 'const char*'

- doc/Jamfile.v2
In the release candidate the algorithm documentation is being built as part of the combined documentation, which means it isn't in its normal location. So this changes it to build as standalone documentation again.
> Build the algorithm documentation standalone.

- include/boost/algorithm/string/detail/find_iterator.hpp
clang warning: extra ';' after member function definition [-Wextra-semi]
> Remove trailing ";"

- minmax/test/minmax_element_test.cpp
- test/partition_subrange_test.cpp
- test/sort_subrange_test.cpp
change std::random_shuffle -> std::shuffle + random_engine if indicated by the supported language level or Boost configuration macro.
Signed-off-by: Daniela Engert <dani@ngrt.de>
> Conditionally replace deprecated c++98 features by c++11 ones

- include/boost/algorithm/algorithm.hpp
`power(x, n, op)` uses `identity_operation` and is constexpr in C++14.
On a tangential note... shouldn't these functions be called `identity_element`?
> Add BOOST_CXX14_CONSTEXPR to identity_operation.

- test/clamp_test.cpp
Signed-off-by: Daniela Engert <dani@ngrt.de>
> functions used in constexpr context must be marked 'constexpr'

- include/boost/algorithm/string/iter_find.hpp
- include/boost/algorithm/string/split.hpp
- string/test/split_test.cpp
On compilers that support C++11, this allows both lvalues and rvalues to be used as inputs to the `split()`, `find_all()`, and `ifind_all()` functions.
For example, given a function `get_string()` that returns a `std::string`, this allows you to write:
```cpp
boost::split(result, get_string(), boost::is_any_of(" "));
```
I'm somewhat surprised that this hasn't been done before, so if I'm missing something, then do let me know. I've hardly done a comprehensive investigation on where else these changes could be made in `boost::algorithm`, so I'm also happy to expand this PR if necessary.
> Use forwarding references in string/split.hpp

- include/boost/algorithm/string/detail/finder.hpp
- include/boost/algorithm/string/detail/trim.hpp
- include/boost/algorithm/string/predicate.hpp
This header is deprecated in favor of `<iterator>` and will be removed in a future release. This silences deprecation warnings.
> Avoid using deprecated header boost/detail/iterator.hpp

- include/boost/algorithm/string/find_format.hpp
- include/boost/algorithm/string/formatter.hpp
- string/example/rle_example.cpp
This is in continuation of https://github.com/boostorg/algorithm/pull/71.
These instances were not detected by tests.
> Remove a few leftover uses of boost/detail/iterator.hpp

- include/boost/algorithm/string/detail/find_format_all.hpp
This patch allows the header to be built standalone, as part of clang C++ modules builds.
> Add missing include

- include/boost/algorithm/string/detail/case_conv.hpp
This patch allows the header to be built standalone, as part of clang C++ modules builds.
> Add missing includes

- include/boost/algorithm/is_clamped.hpp
- test/Jamfile.v2
- test/is_clamped_test.cpp
Hi, 
this is example code for addition of `is_clamped`.
I have never committed to boost, I asked on boost mailing list how to proceed if I want to add `is_clamped `and this was a suggested way to do it.
I did not update the docs, since I first wanted to get a feedback if there is interest in this. 
Few other points.
1.  naming: `is_clamped `is symmetric in STL kind of way but maybe some people would prefer is_between or some other name
2.  formatting: is there some way to automatically format code(like clang-format), it was quite tricky for me to emulate the style of clamp_test.cpp
3. there was(is?) [proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1440r0.html) for std::is_clamped, I am not related to that
4. I have test for `std::string`, normally people use this with …
> Add is_clamped.hpp, is_clamped_test.cpp

- include/boost/algorithm/string/detail/find_iterator.hpp
- include/boost/algorithm/string/find_iterator.hpp
Compiling algorithm/string/test with command ` ../../../../b2 cxxstd=2a "cxxflags=-Werror=deprecated-copy" toolset=gcc-9 -j4` without the patch produces warnings like the following:
```
split_test.cpp:193:14: error: implicitly-declared ‘boost::algorithm::find_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >& boost::algorithm::find_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >::operator=(const boost::algorithm::find_iterator<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> > >&)’ is deprecated [-Werror=deprecated-copy]
193 |     fiter2 = fiter;
|              ^~~~~
```
> Fix -Wdeprecated-copy warnings in string algorithms

- doc/algorithm.qbk
- include/boost/algorithm/cxx11/copy_if.hpp
- test/copy_if_test1.cpp
Problem:
- There is no way to signal that a copy should proceed, selecting
elements by a predicate until some condition is met. This is useful
for patterns along the lines of "copy selected elements until there
are n total elements in the output".
Solution:
- Introduce `copy_if_while()` and `copy_if_until()`.
> Implement copy_if_while and copy_if_until

- test/copy_if_test1.cpp
- test/hex_test4.cpp
- test/is_permutation_test1.cpp
- test/search_test1.cpp
- test/search_test2.cpp
- test/search_test3.cpp
- test/search_test4.cpp
MSVC complains about narrowing conversions and unreferences parameters.
This makes all tests almost level 4 warning clean on MSVC 14.
> Fix MSVC warnings in tests

- include/boost/algorithm/gather.hpp
- include/boost/algorithm/string/classification.hpp
- string/doc/quickref.xml
- string/test/predicate_test.cpp
In string algorithm, is_blank standard classification exists since C++11. Today, this classification is not provided by this library for code.
I have added is_blank functor in the implementation compiled with standard upper or equals to c++11 and complete the documentation.
> Add is_blank() string functor classification
